# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_one', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_two', models.CharField(blank=True, max_length=20, null=True)),
                ('email_one', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_two', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('google_plus_url', models.CharField(blank=True, max_length=255, null=True)),
                ('upword_url', models.CharField(blank=True, max_length=255, null=True)),
                ('github_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
