# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0002_auto_20171126_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
