# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0003_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=b'project/image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='picture_one',
        ),
        migrations.RemoveField(
            model_name='project',
            name='picture_three',
        ),
        migrations.RemoveField(
            model_name='project',
            name='picture_two',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_site.Project'),
        ),
    ]
