# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0005_auto_20171126_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='projectimage',
            old_name='project',
            new_name='project_id',
        ),
    ]
